### ISSUE TITLE
Craft 3 upgrade migration error: Unknown column 'statusId' in 'craft_formbuilder_entries'

### ISSUE THREAD

**Issue by sjcallender** [roundhouse/Form-Builder-3#10]
Running an update from Craft 2 with Form Builder 1.0 to Craft 3.3.7 and Form Builder 3.0.19.

This migration error blocks me from accessing the cp at all.

```
Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'statusId' in 'craft_formbuilder_entries'
The SQL being executed was: ALTER TABLE craft_formbuilder_entries ADD postedOn datetime(0) NOT NULL AFTER statusId

Migration: roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries

Output:

> add column postedOn datetime NOT NULL AFTER statusId to table {{%formbuilder_entries}} ...Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'statusId' in 'craft_formbuilder_entries'
The SQL being executed was: ALTER TABLE craft_formbuilder_entries ADD postedOn datetime(0) NOT NULL AFTER statusId (/Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/roundhouse/form-builder/src/migrations/m181203_214017_AddPostedOnToEntries.php(19): yii\db\Migration->addColumn('{{%formbuilder_...', 'postedOn', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/db/Migration.php(56): roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries->safeUp()
#5 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
#6 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/db/MigrationManager.php(159): craft\db\MigrationManager->migrateUp(Object(roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries))
#7 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#8 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#9 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#14 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/web/Application.php(653): craft\web\Application->runAction('updater/migrate')
#17 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/craftcms/cms/src/web/Application.php(251): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/sjcallender/Sites/shoeshine/FRST/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/sjcallender/Sites/shoeshine/FRST/site/web/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by owldesign** [comment]
Sorry for delay, will fix by end of week

**Comment by owldesign** [comment]
@sjcallender can you tell me the steps you took while you upgraded craft 2 to 3?

Form Builder 2 doesn't have antying to automatically update itsself to version 3. You need to manually install  Form Builder 3 from the plugin store and perform plugin migrations after that (migrate old forms to the new plugin).

**Comment by sjcallender** [comment]
@owldesign Silly mess up. Forgot to run migrations. We're good.
