### ISSUE TITLE
Error after upgrading from craft 2 to 3

### ISSUE THREAD

**Issue by Keishma** [roundhouse/Form-Builder-3#16]
I've successfully upgraded a website from craft 2 to 3. However I have received the following error each time I have tried to add form builder 3. I have looked at [https://github.com/roundhouse/Form-Builder-3/issues/10](url) with no success.

I have tried running the craft upgrade with form builder 2 installed. Then installing form builder 3 manually via the admin panel.

I also tried removing the form builder 2 plugin from the original craft 2 build. Then upgrading to craft 3 and again manually installing form builder 3 via the admin panel. 

Each time I have got the following error:

Any help appreciated, thank you.

> `Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sonnic-new.craft_formbuilder_entries' doesn't exist
> The SQL being executed was: ALTER TABLE craft_formbuilder_entries ADD postedOn datetime(0) NOT NULL AFTER statusId
> 
> Migration: roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries
> 
> Output:

> add column postedOn datetime NOT NULL AFTER statusId to table {{%formbuilder_entries}} ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sonnic-new.craft_formbuilder_entries' doesn't exist
The SQL being executed was: ALTER TABLE craft_formbuilder_entries ADD postedOn datetime(0) NOT NULL AFTER statusId (/Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Applications/MAMP/htdocs/sonnic-new/vendor/roundhouse/form-builder/src/migrations/m181203_214017_AddPostedOnToEntries.php(19): yii\db\Migration->addColumn('{{%formbuilder_...', 'postedOn', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/db/Migration.php(52): roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries->safeUp()
#5 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries))
#7 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#8 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#9 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#14 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#16 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#17 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Applications/MAMP/htdocs/sonnic-new/web/index.php(21): yii\base\Application->run()
#20 {main}`

**Comment by owldesign** [comment]
@Keishma it looks like you are missing table `sonnic-new.craft_formbuilder_entries` in your database, can you verify that that table exist before you try to install or migrate formbuilder 3? That looks like a Craft 2 to 3 migration.

**Comment by Keishma** [comment]
Hi so I've tried again with those columns there before the update: 

![image](https://user-images.githubusercontent.com/33267978/86805575-e428bf80-c06f-11ea-9601-a0a1d1a75663.png)

> `Database Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'statusId' in 'craft_formbuilder_entries'
> The SQL being executed was: ALTER TABLE craft_formbuilder_entries ADD postedOn datetime(0) NOT NULL AFTER statusId
> 
> Migration: roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries
> 
> Output:
> 

> add column postedOn datetime NOT NULL AFTER statusId to table {{%formbuilder_entries}} ...Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'statusId' in 'craft_formbuilder_entries'
The SQL being executed was: ALTER TABLE craft_formbuilder_entries ADD postedOn datetime(0) NOT NULL AFTER statusId (/Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Applications/MAMP/htdocs/sonnic-new/vendor/roundhouse/form-builder/src/migrations/m181203_214017_AddPostedOnToEntries.php(19): yii\db\Migration->addColumn('{{%formbuilder_...', 'postedOn', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/db/Migration.php(52): roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries->safeUp()
#5 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#6 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(roundhouse\formbuilder\migrations\m181203_214017_AddPostedOnToEntries))
#7 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#8 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#9 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/controllers/pluginstore/InstallController.php(118): craft\controllers\BaseUpdaterController->runMigrations(Array)
#10 [internal function]: craft\controllers\pluginstore\InstallController->actionMigrate()
#11 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#14 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('pluginstore/ins...', Array)
#16 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('pluginstore/ins...')
#17 /Applications/MAMP/htdocs/sonnic-new/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Applications/MAMP/htdocs/sonnic-new/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Applications/MAMP/htdocs/sonnic-new/web/index.php(21): yii\base\Application->run()
#20 {main}`

**Comment by owldesign** [comment]
@Keishma thank you, can you also please post screeshoot of the `craft_formbuilder_entries` columns. I want to see if it missed to install specific columns, in this case the missing `statusId`

**Comment by Keishma** [comment]
@owldesign here is the formbuilder_entries structure:

![image](https://user-images.githubusercontent.com/33267978/86909424-f65a3a80-c10f-11ea-862d-b4579fb3b10d.png)

**Comment by adamhenretty** [comment]
I have the same issue I think. The v2 tables and the v3 tables are both in the database, however the v3 forms table is completely empty.

**Comment by owldesign** [comment]
This was fixed back in last November. It was related to table prefixes
