### ISSUE TITLE
error: Calling unknown method: craft\console\Request::getBodyParam()

### ISSUE THREAD

**Issue by petehjfd** [roundhouse/Form-Builder-3#17]
Hi

When running `./craft project-config/sync` during deployment, we are getting the following error:

```
error: Calling unknown method: craft\console\Request::getBodyParam()
```

After looking at Craft's console.log file, it seems that this error is being caused by Form Builder.  Here is the full stack trace:

```
2020-07-13 11:47:46 [-][-][-][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getBodyParam() in /Users/path/to/project/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /Users/path/to/project/vendor/roundhouse/form-builder/src/FormBuilder.php(230): yii\base\Component->__call('getBodyParam', Array)
#1 [internal function]: roundhouse\formbuilder\FormBuilder->roundhouse\formbuilder\{closure}(Object(craft\events\FieldLayoutEvent))
#2 /Users/path/to/project/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\FieldLayoutEvent))
#3 /Users/path/to/project/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveFieldL...', Object(craft\events\FieldLayoutEvent))
#4 /Users/path/to/project/vendor/craftcms/cms/src/services/Fields.php(1320): yii\base\Component->trigger('afterSaveFieldL...', Object(craft\events\FieldLayoutEvent))
#5 /Users/path/to/project/vendor/craftcms/cms/src/services/Sections.php(1232): craft\services\Fields->saveLayout(Object(craft\models\FieldLayout))
#6 /Users/path/to/project/vendor/craftcms/cms/src/services/ProjectConfig.php(1102): craft\services\Sections->handleChangedEntryType(Object(craft\events\ConfigEvent))
#7 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#8 /Users/path/to/project/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#9 /Users/path/to/project/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#10 /Users/path/to/project/vendor/craftcms/cms/src/services/ProjectConfig.php(1092): craft\services\ProjectConfig->processConfigChanges('sections.1a7b7f...')
#11 [internal function]: craft\services\ProjectConfig->handleChangeEvent(Object(craft\events\ConfigEvent))
#12 /Users/path/to/project/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(craft\events\ConfigEvent))
#13 /Users/path/to/project/vendor/craftcms/cms/src/services/ProjectConfig.php(675): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
#14 /Users/path/to/project/vendor/craftcms/cms/src/services/ProjectConfig.php(1204): craft\services\ProjectConfig->processConfigChanges('sections.1a7b7f...', false, NULL, true)
#15 /Users/path/to/project/vendor/craftcms/cms/src/services/ProjectConfig.php(539): craft\services\ProjectConfig->_applyChanges(Array)
#16 /Users/path/to/project/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(87): craft\services\ProjectConfig->applyYamlChanges()
#17 [internal function]: craft\console\controllers\ProjectConfigController->actionSync()
#18 /Users/path/to/project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#19 /Users/path/to/project/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#20 /Users/path/to/project/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('sync', Array)
#21 /Users/path/to/project/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('sync', Array)
#22 /Users/path/to/project/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('sync', Array)
#23 /Users/path/to/project/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#24 /Users/path/to/project/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#25 /Users/path/to/project/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#26 /Users/path/to/project/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#27 /Users/path/to/project/craft(22): yii\base\Application->run()
#28 {main}
```

We are running Craft 3.4.27

**Comment by owldesign** [comment]
I can't seem to recreate this, I wonder if this was eventually resolved on Craft end. the new comman has also changed to `./craft project-config/apply`
